# Generated by Django 5.0.3 on 2024-03-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waddlewaitMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
