# Generated by Django 5.0.3 on 2024-03-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waddlewaitMenu', '0002_alter_menuitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='menu_images/default_image.jpg', upload_to='menu_images/'),
        ),
    ]
