# Generated by Django 5.0.3 on 2024-04-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waddlewaitMenu', '0003_menuitem_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=99999),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='display_order',
            field=models.IntegerField(default=99999),
        ),
    ]
