# Generated by Django 5.0.3 on 2024-04-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0002_alter_assistance_staffname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistance',
            old_name='tableNumber',
            new_name='table',
        ),
    ]
