# Generated by Django 5.0.3 on 2024-04-05 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0003_remove_assistance_tablenumber_assistance_createdtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='staffAcceptedTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
