# Generated by Django 5.0.3 on 2024-04-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0004_assistance_staffacceptedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='staffAcceptedTime',
            field=models.DateTimeField(null=True),
        ),
    ]
