# Generated by Django 5.0.3 on 2024-03-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
