# Generated by Django 5.0.3 on 2024-03-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='deliver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='wait_staff_assigned',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
