# Generated by Django 5.0.3 on 2024-03-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_deliver_orderitem_wait_staff_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=10),
            preserve_default=False,
        ),
    ]
