# Generated by Django 5.0.3 on 2024-03-30 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='deliver',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='wait_staff_assigned',
        ),
        migrations.AddField(
            model_name='order',
            name='deliver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_to_serve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='wait_staff_assigned',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
