# Generated by Django 5.0.3 on 2024-04-01 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_table_order_table_number_and_more'),
    ]

