# Generated by Django 5.0.3 on 2024-04-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billrequest',
            old_name='table',
            new_name='table_number',
        ),
    ]
