# Generated by Django 5.0.3 on 2024-04-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_table_billrequest_table_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table_number',
            new_name='table',
        ),
        migrations.AddField(
            model_name='billrequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billrequest',
            name='staff_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
