# Generated by Django 5.0.3 on 2024-04-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_items'),
        ('orders', '0007_rename_table_billrequest_table_number'),
    ]

    operations = [
    ]
