# Generated by Django 5.0.3 on 2024-04-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20240401_2156'),
        ('orders', '0008_rename_table_number_order_table_and_more'),
    ]

    operations = [
    ]
