# Generated by Django 5.0.3 on 2024-04-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20240401_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table_number',
            new_name='table',
        ),
        migrations.AlterField(
            model_name='billrequest',
            name='staff_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
