# Generated by Django 5.0.3 on 2024-04-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_merge_20240401_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billrequest',
            old_name='table_number',
            new_name='table',
        ),
    ]
