# Generated by Django 5.0.3 on 2024-04-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_merge_20240401_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billrequest',
            old_name='table_number',
            new_name='table',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ready_to_serve',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wait_staff_assigned',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='deliver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_made_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='wait_staff_assigned',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='wait_staff_assigned_time',
            field=models.DateTimeField(null=True),
        ),
    ]
