# Generated by Django 5.0.3 on 2024-04-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_wait_staff_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billrequest',
            name='table',
        ),
        migrations.AddField(
            model_name='billrequest',
            name='table_id',
            field=models.IntegerField(default=1),
        ),
    ]
