# Generated by Django 4.2.11 on 2024-03-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_number', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('table_in_use', models.BooleanField(blank=True)),
                ('seats_max', models.IntegerField(blank=True)),
                ('seats_in_use', models.IntegerField(blank=True)),
                ('order_id', models.IntegerField(blank=True)),
                ('is_near_window', models.BooleanField(blank=True)),
                ('is_quiet_area', models.BooleanField(blank=True)),
            ],
        ),
    ]
