# Generated by Django 4.2.11 on 2024-03-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waddlewait_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order_id',
            field=models.IntegerField(blank=True, default=-1),
            preserve_default=False,
        ),
    ]
