# Generated by Django 5.0.3 on 2024-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waddlewait_app', '0002_table_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
